# Generated by Django 4.1.4 on 2023-01-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('number_page', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoryes',
            },
        ),
    ]
